// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./../App.vue')['default']
    BannerContent: typeof import('./../modules/core/components/banners/BannerContent.vue')['default']
    BannerImage: typeof import('./../modules/core/components/banners/BannerImage.vue')['default']
    ContactInfo: typeof import('./../globals/layouts/default/components/header/ContactInfo.vue')['default']
    DefaultLayout: typeof import('./../globals/layouts/default/layout/DefaultLayout.vue')['default']
    Header: typeof import('./../globals/layouts/default/components/header/Header.vue')['default']
    HomeSection: typeof import('./../modules/core/components/sections/HomeSection.vue')['default']
    LandingPage: typeof import('./../modules/core/pages/LandingPage.vue')['default']
    Loader: typeof import('./../globals/layouts/default/components/Loader.vue')['default']
    NavBar: typeof import('./../globals/layouts/default/components/header/navbar/NavBar.vue')['default']
    NavBarLogo: typeof import('./../globals/layouts/default/components/header/navbar/NavBarLogo.vue')['default']
    NavDropdownLink: typeof import('./../globals/layouts/default/components/header/navbar/NavDropdownLink.vue')['default']
    NavLink: typeof import('./../globals/layouts/default/components/header/navbar/NavLink.vue')['default']
    PageContent: typeof import('./../globals/layouts/default/components/PageContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialIcons: typeof import('./../globals/layouts/default/components/header/SocialIcons.vue')['default']
  }
}

export {}
