// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutSection: typeof import('./../modules/core/components/sections/AboutSection.vue')['default']
    App: typeof import('./../App.vue')['default']
    BannerContent: typeof import('./../modules/core/components/banners/BannerContent.vue')['default']
    BannerImage: typeof import('./../modules/core/components/banners/BannerImage.vue')['default']
    CategoryItem: typeof import('./../modules/core/components/portofolio/categories/CategoryItem.vue')['default']
    CategoryList: typeof import('./../modules/core/components/portofolio/categories/CategoryList.vue')['default']
    ContactInfo: typeof import('./../globals/layouts/default/components/header/ContactInfo.vue')['default']
    DefaultLayout: typeof import('./../globals/layouts/default/layout/DefaultLayout.vue')['default']
    DownloadCVButton: typeof import('./../modules/core/components/buttons/DownloadCVButton.vue')['default']
    EmptyContent: typeof import('./../modules/core/components/shared/EmptyContent.vue')['default']
    Header: typeof import('./../globals/layouts/default/components/header/Header.vue')['default']
    HomeSection: typeof import('./../modules/core/components/sections/HomeSection.vue')['default']
    InformationItem: typeof import('./../modules/core/components/information/InformationItem.vue')['default']
    InformationList: typeof import('./../modules/core/components/information/InformationList.vue')['default']
    LandingPage: typeof import('./../modules/core/pages/LandingPage.vue')['default']
    Loader: typeof import('./../globals/layouts/default/components/Loader.vue')['default']
    NavBar: typeof import('./../globals/layouts/default/components/header/navbar/NavBar.vue')['default']
    NavBarLogo: typeof import('./../globals/layouts/default/components/header/navbar/NavBarLogo.vue')['default']
    NavDropdownLink: typeof import('./../globals/layouts/default/components/header/navbar/NavDropdownLink.vue')['default']
    NavLink: typeof import('./../globals/layouts/default/components/header/navbar/NavLink.vue')['default']
    PageContent: typeof import('./../globals/layouts/default/components/PageContent.vue')['default']
    PortofolioSection: typeof import('./../modules/core/components/sections/PortofolioSection.vue')['default']
    ProjectDetailsModal: typeof import('./../modules/core/components/portofolio/projects/ProjectDetailsModal.vue')['default']
    ProjectItem: typeof import('./../modules/core/components/portofolio/projects/ProjectItem.vue')['default']
    ProjectList: typeof import('./../modules/core/components/portofolio/projects/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareInSocialMedias: typeof import('./../modules/core/components/socials/ShareInSocialMedias.vue')['default']
    SkillItem: typeof import('./../modules/core/components/skills/SkillItem.vue')['default']
    SkillList: typeof import('./../modules/core/components/skills/SkillList.vue')['default']
    SkillSection: typeof import('./../modules/core/components/sections/SkillSection.vue')['default']
    SocialMediaItem: typeof import('./../modules/core/components/socials/SocialMediaItem.vue')['default']
    SocialMedias: typeof import('./../modules/core/components/socials/SocialMedias.vue')['default']
    SocialMediasList: typeof import('./../modules/core/components/socials/SocialMediasList.vue')['default']
  }
}

export {}
